### PR TITLE
Implement Footer component

### PR DESCRIPTION
**Pull request by sarathms**
A static footer with links. Based on the UI mockup.

### CODE REVIEW

**Comment by hellais** [comment]
Great job on the footer! It's perfect. We will perhaps at some point integrate in the ooni-components design system for maximum re-use across all our react based web interfaces.

**Comment by hellais** [comment]
The only thing I would suggest you do is:
- Add the Footer component to the Layout component so that it appears in every page (maybe add an optional prop to disable it via `<Layout disableFooter={true}>`
- Make sure it work properly with pages that don't have enough content on top (i.e. sticky)

**Comment by sarathms** [comment]
> We will perhaps at some point integrate in the ooni-components design system for maximum re-use across all our react based web interfaces.

As we finish building components here, we can move some of them to ooni-components if/when we see possible abstractions. Is that what you also meant?

> Add the Footer component to the Layout component so that it appears in every page (maybe add an optional prop to disable it via <Layout disableFooter={true}>

Good idea.

**Comment by hellais** [comment]
> As we finish building components here, we can move some of them to ooni-components if/when we see possible abstractions. Is that what you also meant?

yes exactly.

> Good idea.

👍

**Pull request merged**
