### PR TITLE
Restore search indicators for circumvention tests

### LINKED ISSUE #520: Show search results indicators for circumvention tests
We should understand if this is possible given the backend

### PR DESCRIPTION
**Pull request by sarathms**
Fixes #520 
Tor tests
image
image
image

Psiphon
image
image
image

### CODE REVIEW

**Comment by sarathms** [comment]
@hellais Should we use `Likely Blocked` as labels in the search results instead of `Anomaly`?

**Comment by hellais** [comment]
> Should we use Likely Blocked as labels in the search results instead of Anomaly?

I think if we do this, we should discuss it broadly for all of the tests. I will add a note about this in the general meeting. For the time being let's keep it as-is.

**Comment by sarathms** [comment]
> For the time being let's keep it as-is.

@hellais Did you get a chance to review this when you posted the comment? Wondering if it is ready to merge.

**Comment by sarathms** [comment]
Updated relevant tests. They all pass now.

**Comment by hellais** [comment]
@sarathms the labels for the circumvention tests are inconsistent with the labels of the other tests.

We should indiciate them all as "Accessible":
Screenshot 2020-12-09 at 11 41 48
Screenshot 2020-12-09 at 11 42 07
Screenshot 2020-12-09 at 11 42 20
Screenshot 2020-12-09 at 11 42 26

**Comment by hellais** [comment]
Once the above change is done, for me this is good to go! 🐳

**Review by hellais — CHANGES_REQUESTED** [review]
Align the labels for Anomaly and Accessible

**Comment by sarathms** [comment]
Now we show the label 'Anomaly' for all the measurements to which it is relevant. Rebased onto master to prepare for merge.

**Pull request merged**
