### PR TITLE
Replace MK specific labels in measurement details box

### LINKED ISSUE #506: Update MK specific measurement details label
As reported by @bassosimone 

## Expected Behavior
The engine behind ooniprobe products for a few months has been the new `probe-engine`. For older probes, this used to be 'measurement-kit'. Measurement pages should specify which engine produced the measurement and the corresponding version number.

## Actual Behavior
Explorer currently shows a MK specific label even for `probe-engine` measurements. e.g in [this measurement](https://explorer.ooni.org/measurement/20200807T222018Z_AS33363_FTKkox83LnAxEXkK8hJQuuqzBjZu2nyTl87aLXQ7MbCPvZIEgW)
image

## Steps to Reproduce the Problem

  1. Open any measurement page.
  2. Scroll to the section right before the raw measurement data

### PR DESCRIPTION
**Pull request by sarathms**
Fixes #506 

image

### CODE REVIEW

**Comment by sarathms** [comment]
@bassosimone It ends up showing this in some cases:
image

msmt: http://explorer.ooni.org/measurement/20201028T115327Z_ndt_GN_37612_n1_UVAWFFGG6osc7NZ4

**Review by bassosimone — APPROVED** [review]
🐳

**Comment by bassosimone** [comment]
@sarathms regarding https://github.com/ooni/explorer/pull/513#issuecomment-718071463, please just replace "OONI Probe" with "Software Name" in the copy and then please merge this fix into master! 🎸

**Comment by sarathms** [comment]
Changed:

**Pull request merged**
