### PR TITLE
Add Traditional Chinese (zh-tw) language

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Add Traditional Chinese (zh-tw) language.

Please note that the efficiency and speed of my translation process are largely attributed to my referencing the existing Simplified Chinese (zh-cn) translations for many of the terms. Let's express gratitude for the contributions made by the Simplified Chinese translations, and also be aware that some terms may require additional fine-tuning.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@majakomel would you like to take a look? Thanks.

**Comment by majakomel** [comment]
Hi @PeterDaveHello, thanks for your contribution! 
We're maintaining our translations on Transifex - https://app.transifex.com/otf/ooni-explorer/dashboard/. 
I will upload your translations as zh-Hant there, you're welcome to join us on Transifex and add other edits there.

**Comment by PeterDaveHello** [comment]
I can upload it there for sure, will need your help to add the language though!

**Comment by majakomel** [comment]
@PeterDaveHello I added `zh-Hant` on Transifex and already uploaded the file. Can you check again if you can access it?

**Comment by PeterDaveHello** [comment]
Hi @majakomel,

I'm still seeing Simplified Chinese on my Android, which is set to use Traditional Chinese. Is there anything I can do to make my translation available for Traditional Chinese users?

**Comment by PeterDaveHello** [comment]
Oh, I might be wrong, that's not the probe repository, sorry!

**Pull request closed without merging**
