### PR TITLE
Measurement aggregation toolkit - previously nivo-toy

### LINKED ISSUE #528: Improve the Measurement Aggregation Toolkit
We have started working on a generic web-based tool that can help with creating useful visualizations with aggregated measurement data from the API. It is currently deployed in the experimental garage of OONI Explorer. (https://explorer.ooni.org/experimental/aggregation). The interactive one is currently [here](https://explorer.ooni.org/nivo-toy) (and will be moved to the earlier link).

With @hellais, we discussed a bunch of improvements we can do for the next iteration:

- [x] Rename to experimental/aggregation
- [x] Add drop-down for probe_cc, category_code
- [x] Date selector
- [x] Replace domain with input
- [x] Add query params to URL bar
- ~[ ] Add support for axis_y plotting~
- ~[ ] One heatmap each for `anomaly_count` and `confirmed_count`~
- - ~[ ] Build upon that a single heatmap with both values in each cell~

### PR DESCRIPTION
**Pull request by sarathms**
Fixes #528

### CODE REVIEW

**Comment by hellais** [comment]
When I load the page all I see is the following:

Screenshot 2020-12-11 at 15 09 41

There is also a 404 error on the styles.css

**Review by hellais — CHANGES_REQUESTED** [review]
I am not able to load the page.

**Comment by sarathms** [comment]
This is still in draft stage. I added you as reviewer thinking it will notify when change the state to ready. Sorry about the confusion.

Also the page is `/experimental/mat`. Feel free to suggest a better name. This one is more sensible than 'nivo-toy' but also rather boring.

**Comment by sarathms** [comment]
The form needs some re-arrangement to save some space. Or maybe make it collapsible. Will do that after the functionality is done.

image

**Comment by sarathms** [comment]
You can track progress in the checklist on #528

**Comment by sarathms** [comment]
Merging this at this point. The 2-axis charting will be implemented in #536

**Comment by sarathms** [comment]
Rebased onto master. Ready to merge.

**Pull request merged**
