### PR TITLE
fix(Stats.js): display correct monthly measurements after changing language

### LINKED ISSUE #873: OONI Explorer starting page shows 0 monthly measurements in the localized versions of the page
## Expected Behavior

All localized pages should be showing the same number of monthly measurements as the source one (English)

Screenshot 2023-10-11 at 16 07 59

## Actual Behavior

Localized pages show 0 measurements.

Screenshot 2023-10-11 at 15 58 13
Screenshot 2023-10-11 at 16 08 13
Screenshot 2023-10-11 at 16 09 51

## Steps to Reproduce the Problem

  1. Open https://explorer.ooni.org/
  2. Set language to any language other than English, e.g. https://explorer.ooni.org/ru
  3. Scroll down to the 'Monthly coverage worldwide' section

## Specifications

  - Version:
  - Platform:
  - Subsystem:

### PR DESCRIPTION
**Pull request by Lanius-collaris**
Fixes #873

### CODE REVIEW

**Comment by Lanius-collaris** [comment]
ping @majakomel

**Comment by Lanius-collaris** [comment]
@sloncocs 🥲Could you review #886 and #884 ?

**Comment by sloncocs** [comment]
> @sloncocs 🥲Could you review #886 and #884 ?

unfortunately, I cannot as I am not a developer 😢  but I think the right person to tag here is @jbonisteel

**Comment by Lanius-collaris** [comment]
🥲This patch doesn't work for master. Checking...

**Comment by Lanius-collaris** [comment]
> 🥲This patch doesn't work for master. Checking...

`dt.getUTCFullYear() === today.getUTCFullYear()`
🤣 In January, you can't see get last month data...
https://github.com/ooni/explorer/blob/b2f2333c723fb632cf9af3b489845ed82e956ddd/components/landing/Stats.js#L43-L50

**Review by majakomel — APPROVED** [review]
LGTM! Thanks for fixing the bugs!

**Pull request merged**
