### PR TITLE
Show consistent url in search result

### LINKED ISSUE #114: Search page - Consistently show the full tested URL
When viewing Web Connectivity results from the Search page, some measurements show the tested URL (e.g. https://imageshack.com), while others show the tested domain (e.g. www.gmch.org). For example:

urls-vs-domains

Please display tested URLs consistently across all measurements.

### PR DESCRIPTION
**Pull request by sarathms**
Closes #114

### CODE REVIEW

**Comment by sarathms** [comment]
image

**Comment by hellais** [comment]
Can you deploy this to the beta so I can check it?

**Comment by sarathms** [comment]
Deployed!

**Comment by hellais** [comment]
LGTM!

**Pull request merged**
