### PR TITLE
adding git inside the container

### PR DESCRIPTION
**Pull request by GermaVinsmoke**
Signed-off-by: GermaVinsmoke <vaibhav1180@gmail.com>

### CODE REVIEW

**Comment by majakomel** [comment]
Just adding git is unfortunately not going to be enough with our current build process - there are other changes needed in the build script we use. 
I'm working on other build improvements here (still WIP) https://github.com/ooni/explorer/pull/808

**Comment by GermaVinsmoke** [comment]
But when I tested with the current `DockerFile`, it was giving `git not found`.
On installing git inside the builder container, it was able to run those `yarn --silent` commands successfully 🤔

**Comment by majakomel** [comment]
Yes, we need to add git, but it is not the only thing required for it to work, since we [currently run it against git archive](https://github.com/ooni/sysadmin/blob/master/scripts/docker-build), which is "not a git repository" (doesn't contain .git folder). I also found out there are some other optimizations we can do to drastically decrease docker image size.

**Comment by GermaVinsmoke** [comment]
That means, even the previous `./git-populate-env.sh` script was wrong for populating the git env variables 🤔

**Comment by majakomel** [comment]
Closing this since it's included in https://github.com/ooni/explorer/pull/808

**Pull request closed without merging**
